services:
  backend:
    build:
      context: ./
    container_name: order-service
    env_file: ".env"
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    networks:
      - backend
    command: sh -c "npm run typeorm:run && node dist/main"
  
  db:
    image: postgres:14.17
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${ORDER_DB_NAME}
      POSTGRES_USER: ${ORDER_DB_USER_NAME}
      POSTGRES_PASSWORD: ${ORDER_DB_USER_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 20s
      timeout: 20s
      retries: 5
      start_period: 30s
    networks:
      - backend

volumes:
  db-data:    
  
networks:
  backend:
    driver: bridge
